Finger Curl Calculation Addition
provencher/MRTK-Quest pull request #65
Opened 2020-07-05 15:57 UTC by chetu3319

Adding functions to calculate the curl of fingers. 
Example usage: 
```
// Compute the curl of Index Finger of Right Hand
float indexCurl =  HandPoseUtils.IndexCurl(Handedness.Right);
```

Output ranges from 0 (No-Curl) to 1 (Fully-Curled) finger.

2020-07-05 16:11 UTC, provencher requested changes
Code looks great! Some minor changes.
If you can post a gif or a screenshot of what the scene changes look like, it would be great.

2020-07-05 16:11 UTC, provencher commented on Assets/MRTK.ThirdParty/MRTK-Quest/Scripts/Debug/FingerCurlExample.cs
> +
please remove some of the white space here.

2020-07-05 16:11 UTC, provencher commented on Assets/MRTK.ThirdParty/MRTK-Quest/Scripts/Utils/HandPoseUtils.cs
> +
Please remove one white space here. Try not to keep more than one blank line before spaced out areas here.

2020-07-05 16:11 UTC, provencher commented on Assets/MRTK.ThirdParty/MRTK-Quest/Scripts/Debug/FingerCurlExample.cs
> +    public GameObject indexFinger;
My preference is to have private serialized fields.

2020-07-05 16:11 UTC, provencher commented on Assets/MRTK.ThirdParty/MRTK-Quest/Scripts/Debug/FingerCurlExample.cs
> +public class FingerCurlExample : MonoBehaviour
Please add a namespace for this class. See the other debug sample classes

2020-07-05 16:11 UTC, provencher commented on Assets/MRTK.ThirdParty/MRTK-Quest/Scripts/Debug/FingerCurlExample.cs
> +﻿using System.Collections;
Please add a header here spelling out the license and such. See other classes in this project for a reference.

2020-07-05 16:18 UTC, provencher commented on Assets/MRTK.ThirdParty/MRTK-Quest/Scripts/Utils/HandPoseUtils.cs
> +            var curl = Vector3.Dot(fingerKnuckleToTip, palmToFinger);
Clever approach to do a dot product here!

2020-07-09 05:31 UTC, chetu3319 commented
I've made the suggested updates of calculating `gripStrength` from the finger's curl value. 
I carried two different calculation: 
1. Only considering the index and middle finger's curl value. Works for full hand grip, but provides a false visual cue when only that two fingers are curled. 
2. Considering all four fingers' curl value. Works perfectly providing intended visual cue.

2020-07-09 14:08 UTC, provencher approved these changes

2020-07-09 14:09 UTC, merged